# Generated by Django 5.0.2 on 2024-02-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto1', models.CharField(max_length=100)),
                ('texto2', models.CharField(max_length=100)),
                ('texto3', models.CharField(max_length=100)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='perfil/')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=128, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(max_length=20, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=150, unique=True, verbose_name='Usuario'),
        ),
    ]
