# Generated by Django 5.0.2 on 2024-03-01 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfil_alter_usuario_contrasena_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-created'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2023-02-28 14:30:00', verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='perfil'),
        ),
    ]
