# Generated by Django 5.0.2 on 2024-03-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_perfil_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='texto1',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='texto2',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='texto3',
            field=models.CharField(max_length=160),
        ),
    ]
