# Generated by Django 5.0.2 on 2024-03-09 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_options_usuario_created_usuario_estado_and_more'),
        ('core', '0005_usuario_estado_usuario_tipo_usuario_datos'),
    ]

    operations = [
    ]
