# Generated by Django 5.0.2 on 2024-03-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20240308_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='en_linea',
            field=models.BooleanField(default=False),
        ),
    ]
