# Generated by Django 5.0.2 on 2024-03-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usuario_en_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='session_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
