# Generated by Django 4.2.8 on 2024-03-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_conversation_messageindividual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'Conversacion', 'verbose_name_plural': 'Conversaciones'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='messageindividual',
            options={'verbose_name': 'Mensaje Individual', 'verbose_name_plural': 'Mensajes Individuales'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
    ]
