# Generated by Django 4.2.8 on 2024-03-26 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_transmision_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia_Destacada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Historia1', models.ImageField(blank=True, null=True, upload_to='historia_destacada')),
                ('Historia2', models.ImageField(blank=True, null=True, upload_to='historia_destacada')),
                ('Historia3', models.ImageField(blank=True, null=True, upload_to='historia_destacada')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Historia_Destacada',
                'verbose_name_plural': 'Historias_Destacadas',
            },
        ),
    ]
