# Generated by Django 4.2.8 on 2024-03-26 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historia_destacada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcriptores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(blank=True, related_name='subcriptores_joined', to='core.usuario', verbose_name='Subcriptores')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Subcripcion',
                'verbose_name_plural': 'Subcripciones',
            },
        ),
    ]
