# Generated by Django 4.2.8 on 2024-03-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_subcriptores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcriptores',
            old_name='users',
            new_name='sub',
        ),
    ]
