# Generated by Django 4.2.8 on 2024-03-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_users_subcriptores_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='vista',
            field=models.ManyToManyField(blank=True, related_name='vista_joined', to='core.usuario', verbose_name='Vistas'),
        ),
    ]
