# Generated by Django 4.2.8 on 2024-03-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_historia_destacada_vista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobreNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oportunidad', models.TextField()),
                ('politicas', models.TextField()),
                ('mision', models.TextField()),
            ],
        ),
    ]
