# Generated by Django 4.2.8 on 2024-04-01 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_sobrenosotros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opiniones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.TextField(verbose_name='Opinion')),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
