# Generated by Django 4.2.8 on 2024-04-01 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_opiniones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opiniones',
            options={'verbose_name': 'Opinion', 'verbose_name_plural': 'Opiniones'},
        ),
        migrations.AlterField(
            model_name='opiniones',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario', verbose_name='Usuario'),
        ),
    ]
