# Generated by Django 4.2.8 on 2024-04-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='pub',
            field=models.FileField(blank=True, null=True, upload_to='publicacion', verbose_name='Imagen o Video'),
        ),
    ]
