# Generated by Django 4.2.8 on 2024-04-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_publicacion_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='Historias', verbose_name='Imagen o Video'),
        ),
    ]
