# Generated by Django 4.2.8 on 2024-04-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_historia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_destacada',
            name='Historia1',
            field=models.FileField(blank=True, null=True, upload_to='historia_destacada', verbose_name='Imagen o Video'),
        ),
        migrations.AlterField(
            model_name='historia_destacada',
            name='Historia2',
            field=models.FileField(blank=True, null=True, upload_to='historia_destacada', verbose_name='Imagen o Video'),
        ),
        migrations.AlterField(
            model_name='historia_destacada',
            name='Historia3',
            field=models.FileField(blank=True, null=True, upload_to='historia_destacada', verbose_name='Imagen o Video'),
        ),
    ]
