from django.urls import path
from .views import *

urlpatterns = [
    path('', Login.as_view(), name="login"),
    path('registro/', Registro.as_view(), name="registro"),
    path('Inicio/', Inicio.as_view(), name="Inicio"), 
    path('soporte/', Soporte.as_view(), name="soporte"),
    path('contenido/', Contenido.as_view(), name="contenido"),
    path('sobrenosotros/', sobrenosotros.as_view(), name="sobrenosotros"),
    path('view-history/<str:usuario>/', ViewHistory.as_view(), name="viewhistory"),
    path('view-historyd/<str:usuario>/<id>/', ViewHistoryD.as_view(), name="viewhistoryd"),
    path('perfil/', MIPerfil.as_view(), name="perfil"),
    path('registrocreador/<user>', RegistroC.as_view(), name="registroc"),
    path('Perfil/<user>', Perfil.as_view(), name="Perfil"),
    path('perfilcontenido/', Miperfilcontenido.as_view(), name="perfilcontenido"),
    path('Perfilcontenido/<user>', Perfilcontenido.as_view(), name="Perfilcontenido"),
    path('view_perfil/', view_perfil.as_view(), name="viewperfil"),
    path('view_perfild/', view_perfild.as_view(), name="viewperfild"),
    path('upload-images/', upload_images, name='upload-images'),
    path('upload-video/', upload_video, name='upload_video'),
    path('cargar_op/', cargar_opinion, name='cargarop'),
    path('cargar_pub/', cargar_pub, name='cargarpub'),
    path('editar_pub/', edit_pub, name='editarpub'),
    path('view-pub/<int:id>/<tip>', ViewPub.as_view(), name="viewpub"),
    path('view-pubn/<user>/<int:id>/', ViewPubn.as_view(), name="viewpubn"),
    path('email/', cod_mail, name="email"), 
    path('emailN/<usuario>', not_mail, name="emailN"), 
    path('logout/', cerrar_sesion, name="logout"),
    path('get_old_message/', get_old_messages, name='get_old_message'),
    path('get_old_messages/<crv_id>/', get_old_messages_individual, name='get_old_messages_individual'),
    path('agg_sub/<user>/', agregar_subscriptor, name='agg_sub'),
    path('agg_view/<usuario>/', vistas, name='agg_view'),
    path('agg_viewd/<usuario>/<id>/', vistasd, name='agg_viewd'),
    path('pago/<user>/', pago.as_view(), name='pago'),
    path('list/', streaming_view, name='lista_transmisiones'),
    path('ver/<name>/', watch_streaming_view, name='ver_transmision'),
    path('nueva/<name>/', streaming_view, name='nueva_transmision'),
    path('api/orders', create_order, name='create_order'),
    path('api/orders/<str:order_id>/capture', capture_order, name='capture_order'),
]